/*
 * Java bean class for entity table  
 * Created on 6 janv. 2016 ( Date ISO 2016-01-06 - Time 18:22:18 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package org.demo.bean;

import java.io.Serializable;

import java.util.Date;

/**
 * Entity bean for table ""
 * 
 * @author Telosys Tools Generator
 *
 */
public class Author implements Serializable
{
    private static final long serialVersionUID = 1L;


    private Date       birthdate    ;
    private String     lastname     ;
    private String     firstname    ;

    /**
     * Default constructor
     */
    public Author()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING :  (  ) 
    /**
     * Set the "birthdate" field value
     * This field is mapped on the database column "" ( type "", NotNull : false ) 
     * @param birthdate
     */
    public void setBirthdate( Date birthdate )
    {
        this.birthdate = birthdate;
    }
    /**
     * Get the "birthdate" field value
     * This field is mapped on the database column "" ( type "", NotNull : false ) 
     * @return the field value
     */
    public Date getBirthdate()
    {
        return this.birthdate;
    }

    //--- DATABASE MAPPING :  (  ) 
    /**
     * Set the "lastname" field value
     * This field is mapped on the database column "" ( type "", NotNull : false ) 
     * @param lastname
     */
    public void setLastname( String lastname )
    {
        this.lastname = lastname;
    }
    /**
     * Get the "lastname" field value
     * This field is mapped on the database column "" ( type "", NotNull : false ) 
     * @return the field value
     */
    public String getLastname()
    {
        return this.lastname;
    }

    //--- DATABASE MAPPING :  (  ) 
    /**
     * Set the "firstname" field value
     * This field is mapped on the database column "" ( type "", NotNull : false ) 
     * @param firstname
     */
    public void setFirstname( String firstname )
    {
        this.firstname = firstname;
    }
    /**
     * Get the "firstname" field value
     * This field is mapped on the database column "" ( type "", NotNull : false ) 
     * @return the field value
     */
    public String getFirstname()
    {
        return this.firstname;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(birthdate);
        sb.append("|");
        sb.append(lastname);
        sb.append("|");
        sb.append(firstname);
        return sb.toString(); 
    } 


}
